import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CRTOverlay from "./components/shared/CRTOverlay";
import BottomNavigation from "./components/shared/BottomNavigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-black `}
    >
      <body className="min-h-full flex flex-col bg-black text-white p-4 md:p-8 overflow-hidden">
        <div className="relative w-full h-full flex flex-col crt-curve overflow-hidden bg-[#E5E5E5]">
          <CRTOverlay />
          <BottomNavigation />

          <main className="flex-1 overflow-auto relative z-10">{children}</main>
        </div>
      </body>
    </html>
  );
}
